AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 20
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://proj-input/faf66e502169b8a5ac8cbbcb012ae4a0
      Handler: aws_run.lambda_handler
      Runtime: python3.7
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /
            Method: get
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
